Event Interactions
dyamijr/Slideee pull request #32
Opened 2023-11-03 20:19 UTC by jeda234

Backend code related to liking/un-liking an event, sliding/un-sliding an event, and creating/editing/deleting a comment.
Changes included:
- Creating functions in users.services to update array containing liked and slid events for a unique user
- Creating functions in events.services to;
  - Update the event like and slide counter
  - Create a new comment
    - Update said comment
    - Delete said comment
- Creating a comment schema

2023-11-05 21:19 UTC, dyamijr requested changes
Nice job overall. Just fix the suggested changes and then this is good to go.

2023-11-05 21:19 UTC, dyamijr commented on backend/src/events/events.service.ts
All functions should return the eventid after a successful action. Comment functions should return the comment id.

2023-11-05 21:19 UTC, dyamijr commented on backend/src/events/events.controller.ts
> +    const event = await this.eventsService.commentEvent(id, comment.content, req.user);
for the comment functions change event to comment just to clear up any possible confusion.

2023-11-05 21:19 UTC, dyamijr commented on backend/src/schemas/user.schema.ts
The likedEvents and slidEvents should be types of mongoose.Types.ObjectId[]. See comments or collaborators in event schema.

2023-11-05 21:19 UTC, dyamijr commented on backend/src/events/events.service.ts
> +      this.userService.likeEvent(id, uid);
for like event to take in a monoose object you should send the event._id

2023-11-05 21:19 UTC, dyamijr commented on backend/src/users/users.service.ts
> +  async likeEvent(id: String, uid: mongoose.Types.ObjectId) {
change id name to eventId and its type to mongoose.Types.ObjectId

2023-11-05 21:19 UTC, dyamijr commented on backend/src/users/users.service.ts
> +    const user = await this.userModel.findById(uid);
should also add a check to make sure the user exist.

2023-11-05 21:19 UTC, dyamijr commented on backend/src/users/users.service.ts
> +    console.log('test')
remove this

2023-11-05 21:19 UTC, dyamijr commented on backend/src/users/users.service.ts
apply changes mentioned in like event to all functions it applies to

2023-11-06 22:53 UTC, jeda234 commented
Changes added

2023-11-07 04:48 UTC, dyamijr approved these changes
Looks great

2023-11-07 04:49 UTC, merged